#ifndef __RESOURCE_MAP_H__
#define __RESOURCE_MAP_H__

#include <stdint.h>

// =================================================
//  Auto-generated by bsp_resource_packer.py
//  Timestamp: 2026-02-17 22:21:55
//  Base Address: 0x00000000
// =================================================

// Source: resources/test.bin
#define RES_IMG_TEST_OFFSET   (0x00000000)
#define RES_IMG_TEST_ADDR     (0x00000000)
#define RES_IMG_TEST_SIZE     (153604)
#define RES_IMG_TEST_ALIGNED  (153604)

// Source: resources/huahai.bin
#define RES_IMG_huahai_OFFSET   (0x00025804)
#define RES_IMG_huahai_ADDR     (0x00025804)
#define RES_IMG_huahai_SIZE     (153604)
#define RES_IMG_huahai_ALIGNED  (153604)

// Source: resources/font_cn_24.bin
#define font_cn_24_OFFSET   (0x0004B008)
#define font_cn_24_ADDR     (0x0004B008)
#define font_cn_24_SIZE     (10280)
#define font_cn_24_ALIGNED  (10280)

// Source: resources/font_cn_16.bin
#define font_cn_16_OFFSET   (0x0004D830)
#define font_cn_16_ADDR     (0x0004D830)
#define font_cn_16_SIZE     (23028)
#define font_cn_16_ALIGNED  (23028)

// Source: resources/gif0.bin
#define gif0_OFFSET   (0x00053224)
#define gif0_ADDR     (0x00053224)
#define gif0_SIZE     (1204)
#define gif0_ALIGNED  (1204)

// Source: resources/gif1.bin
#define gif1_OFFSET   (0x000536D8)
#define gif1_ADDR     (0x000536D8)
#define gif1_SIZE     (1204)
#define gif1_ALIGNED  (1204)

// Source: resources/gif2.bin
#define gif2_OFFSET   (0x00053B8C)
#define gif2_ADDR     (0x00053B8C)
#define gif2_SIZE     (1204)
#define gif2_ALIGNED  (1204)

// Source: resources/gif3.bin
#define gif3_OFFSET   (0x00054040)
#define gif3_ADDR     (0x00054040)
#define gif3_SIZE     (1204)
#define gif3_ALIGNED  (1204)

// Source: resources/gif4.bin
#define gif4_OFFSET   (0x000544F4)
#define gif4_ADDR     (0x000544F4)
#define gif4_SIZE     (1204)
#define gif4_ALIGNED  (1204)

// Source: resources/frame_00_delay-0.bin
#define frame_00_OFFSET   (0x000549A8)
#define frame_00_ADDR     (0x000549A8)
#define frame_00_SIZE     (24304)
#define frame_00_ALIGNED  (24304)

// Source: resources/frame_01_delay-0.bin
#define frame_01_OFFSET   (0x0005A898)
#define frame_01_ADDR     (0x0005A898)
#define frame_01_SIZE     (24304)
#define frame_01_ALIGNED  (24304)

// Source: resources/frame_02_delay-0.bin
#define frame_02_OFFSET   (0x00060788)
#define frame_02_ADDR     (0x00060788)
#define frame_02_SIZE     (24304)
#define frame_02_ALIGNED  (24304)

// Source: resources/frame_03_delay-0.bin
#define frame_03_OFFSET   (0x00066678)
#define frame_03_ADDR     (0x00066678)
#define frame_03_SIZE     (24304)
#define frame_03_ALIGNED  (24304)

// Source: resources/frame_04_delay-0.bin
#define frame_04_OFFSET   (0x0006C568)
#define frame_04_ADDR     (0x0006C568)
#define frame_04_SIZE     (24304)
#define frame_04_ALIGNED  (24304)

// Source: resources/frame_05_delay-0.bin
#define frame_05_OFFSET   (0x00072458)
#define frame_05_ADDR     (0x00072458)
#define frame_05_SIZE     (24304)
#define frame_05_ALIGNED  (24304)

// Source: resources/frame_06_delay-0.bin
#define frame_06_OFFSET   (0x00078348)
#define frame_06_ADDR     (0x00078348)
#define frame_06_SIZE     (24304)
#define frame_06_ALIGNED  (24304)

// Source: resources/frame_07_delay-0.bin
#define frame_07_OFFSET   (0x0007E238)
#define frame_07_ADDR     (0x0007E238)
#define frame_07_SIZE     (24304)
#define frame_07_ALIGNED  (24304)

// Source: resources/frame_08_delay-0.bin
#define frame_08_OFFSET   (0x00084128)
#define frame_08_ADDR     (0x00084128)
#define frame_08_SIZE     (24304)
#define frame_08_ALIGNED  (24304)

// Source: resources/frame_09_delay-0.bin
#define frame_09_OFFSET   (0x0008A018)
#define frame_09_ADDR     (0x0008A018)
#define frame_09_SIZE     (24304)
#define frame_09_ALIGNED  (24304)

// Source: resources/frame_10_delay-0.bin
#define frame_10_OFFSET   (0x0008FF08)
#define frame_10_ADDR     (0x0008FF08)
#define frame_10_SIZE     (24304)
#define frame_10_ALIGNED  (24304)

// Source: resources/frame_11_delay-0.bin
#define frame_11_OFFSET   (0x00095DF8)
#define frame_11_ADDR     (0x00095DF8)
#define frame_11_SIZE     (24304)
#define frame_11_ALIGNED  (24304)

// Source: resources/frame_12_delay-0.bin
#define frame_12_OFFSET   (0x0009BCE8)
#define frame_12_ADDR     (0x0009BCE8)
#define frame_12_SIZE     (24304)
#define frame_12_ALIGNED  (24304)

// Source: resources/frame_13_delay-0.bin
#define frame_13_OFFSET   (0x000A1BD8)
#define frame_13_ADDR     (0x000A1BD8)
#define frame_13_SIZE     (24304)
#define frame_13_ALIGNED  (24304)

// Source: resources/frame_14_delay-0.bin
#define frame_14_OFFSET   (0x000A7AC8)
#define frame_14_ADDR     (0x000A7AC8)
#define frame_14_SIZE     (24304)
#define frame_14_ALIGNED  (24304)

// Source: resources/frame_15_delay-0.bin
#define frame_15_OFFSET   (0x000AD9B8)
#define frame_15_ADDR     (0x000AD9B8)
#define frame_15_SIZE     (24304)
#define frame_15_ALIGNED  (24304)

// Source: resources/frame_16_delay-0.bin
#define frame_16_OFFSET   (0x000B38A8)
#define frame_16_ADDR     (0x000B38A8)
#define frame_16_SIZE     (24304)
#define frame_16_ALIGNED  (24304)

// Source: resources/frame_17_delay-0.bin
#define frame_17_OFFSET   (0x000B9798)
#define frame_17_ADDR     (0x000B9798)
#define frame_17_SIZE     (24304)
#define frame_17_ALIGNED  (24304)

// Source: resources/frame_18_delay-0.bin
#define frame_18_OFFSET   (0x000BF688)
#define frame_18_ADDR     (0x000BF688)
#define frame_18_SIZE     (24304)
#define frame_18_ALIGNED  (24304)

// Source: resources/frame_19_delay-0.bin
#define frame_19_OFFSET   (0x000C5578)
#define frame_19_ADDR     (0x000C5578)
#define frame_19_SIZE     (24304)
#define frame_19_ALIGNED  (24304)

// Source: resources/frame_20_delay-0.bin
#define frame_20_OFFSET   (0x000CB468)
#define frame_20_ADDR     (0x000CB468)
#define frame_20_SIZE     (24304)
#define frame_20_ALIGNED  (24304)

// Source: resources/frame_21_delay-0.bin
#define frame_21_OFFSET   (0x000D1358)
#define frame_21_ADDR     (0x000D1358)
#define frame_21_SIZE     (24304)
#define frame_21_ALIGNED  (24304)

// Source: resources/frame_22_delay-0.bin
#define frame_22_OFFSET   (0x000D7248)
#define frame_22_ADDR     (0x000D7248)
#define frame_22_SIZE     (24304)
#define frame_22_ALIGNED  (24304)

// Source: resources/frame_23_delay-0.bin
#define frame_23_OFFSET   (0x000DD138)
#define frame_23_ADDR     (0x000DD138)
#define frame_23_SIZE     (24304)
#define frame_23_ALIGNED  (24304)

// Source: resources/frame_24_delay-0.bin
#define frame_24_OFFSET   (0x000E3028)
#define frame_24_ADDR     (0x000E3028)
#define frame_24_SIZE     (24304)
#define frame_24_ALIGNED  (24304)

// Source: resources/frame_25_delay-0.bin
#define frame_25_OFFSET   (0x000E8F18)
#define frame_25_ADDR     (0x000E8F18)
#define frame_25_SIZE     (24304)
#define frame_25_ALIGNED  (24304)

// Source: resources/frame_26_delay-0.bin
#define frame_26_OFFSET   (0x000EEE08)
#define frame_26_ADDR     (0x000EEE08)
#define frame_26_SIZE     (24304)
#define frame_26_ALIGNED  (24304)

// Source: resources/frame_27_delay-0.bin
#define frame_27_OFFSET   (0x000F4CF8)
#define frame_27_ADDR     (0x000F4CF8)
#define frame_27_SIZE     (24304)
#define frame_27_ALIGNED  (24304)

// Source: resources/frame_28_delay-0.bin
#define frame_28_OFFSET   (0x000FABE8)
#define frame_28_ADDR     (0x000FABE8)
#define frame_28_SIZE     (24304)
#define frame_28_ALIGNED  (24304)

// Source: resources/frame_29_delay-0.bin
#define frame_29_OFFSET   (0x00100AD8)
#define frame_29_ADDR     (0x00100AD8)
#define frame_29_SIZE     (24304)
#define frame_29_ALIGNED  (24304)

// Source: resources/frame_30_delay-0.bin
#define frame_30_OFFSET   (0x001069C8)
#define frame_30_ADDR     (0x001069C8)
#define frame_30_SIZE     (24304)
#define frame_30_ALIGNED  (24304)

// Source: resources/frame_31_delay-0.bin
#define frame_31_OFFSET   (0x0010C8B8)
#define frame_31_ADDR     (0x0010C8B8)
#define frame_31_SIZE     (24304)
#define frame_31_ALIGNED  (24304)

// Source: resources/frame_32_delay-0.bin
#define frame_32_OFFSET   (0x001127A8)
#define frame_32_ADDR     (0x001127A8)
#define frame_32_SIZE     (24304)
#define frame_32_ALIGNED  (24304)

// Source: resources/frame_33_delay-0.bin
#define frame_33_OFFSET   (0x00118698)
#define frame_33_ADDR     (0x00118698)
#define frame_33_SIZE     (24304)
#define frame_33_ALIGNED  (24304)

// Source: resources/frame_34_delay-0.bin
#define frame_34_OFFSET   (0x0011E588)
#define frame_34_ADDR     (0x0011E588)
#define frame_34_SIZE     (24304)
#define frame_34_ALIGNED  (24304)

// Source: resources/frame_35_delay-0.bin
#define frame_35_OFFSET   (0x00124478)
#define frame_35_ADDR     (0x00124478)
#define frame_35_SIZE     (24304)
#define frame_35_ALIGNED  (24304)

// Source: resources/frame_36_delay-0.bin
#define frame_36_OFFSET   (0x0012A368)
#define frame_36_ADDR     (0x0012A368)
#define frame_36_SIZE     (24304)
#define frame_36_ALIGNED  (24304)

// Source: resources/frame_37_delay-0.bin
#define frame_37_OFFSET   (0x00130258)
#define frame_37_ADDR     (0x00130258)
#define frame_37_SIZE     (24304)
#define frame_37_ALIGNED  (24304)

// Source: resources/frame_38_delay-0.bin
#define frame_38_OFFSET   (0x00136148)
#define frame_38_ADDR     (0x00136148)
#define frame_38_SIZE     (24304)
#define frame_38_ALIGNED  (24304)

// Source: resources/frame_39_delay-0.bin
#define frame_39_OFFSET   (0x0013C038)
#define frame_39_ADDR     (0x0013C038)
#define frame_39_SIZE     (24304)
#define frame_39_ALIGNED  (24304)

// Source: resources/frame_40_delay-0.bin
#define frame_40_OFFSET   (0x00141F28)
#define frame_40_ADDR     (0x00141F28)
#define frame_40_SIZE     (24304)
#define frame_40_ALIGNED  (24304)

// Source: resources/frame_41_delay-0.bin
#define frame_41_OFFSET   (0x00147E18)
#define frame_41_ADDR     (0x00147E18)
#define frame_41_SIZE     (24304)
#define frame_41_ALIGNED  (24304)

// Source: resources/frame_42_delay-0.bin
#define frame_42_OFFSET   (0x0014DD08)
#define frame_42_ADDR     (0x0014DD08)
#define frame_42_SIZE     (24304)
#define frame_42_ALIGNED  (24304)

// Source: resources/frame_43_delay-0.bin
#define frame_43_OFFSET   (0x00153BF8)
#define frame_43_ADDR     (0x00153BF8)
#define frame_43_SIZE     (24304)
#define frame_43_ALIGNED  (24304)

// Source: resources/frame_44_delay-0.bin
#define frame_44_OFFSET   (0x00159AE8)
#define frame_44_ADDR     (0x00159AE8)
#define frame_44_SIZE     (24304)
#define frame_44_ALIGNED  (24304)

// Source: resources/frame_45_delay-0.bin
#define frame_45_OFFSET   (0x0015F9D8)
#define frame_45_ADDR     (0x0015F9D8)
#define frame_45_SIZE     (24304)
#define frame_45_ALIGNED  (24304)

// Source: resources/frame_46_delay-0.bin
#define frame_46_OFFSET   (0x001658C8)
#define frame_46_ADDR     (0x001658C8)
#define frame_46_SIZE     (24304)
#define frame_46_ALIGNED  (24304)

// Source: resources/frame_47_delay-0.bin
#define frame_47_OFFSET   (0x0016B7B8)
#define frame_47_ADDR     (0x0016B7B8)
#define frame_47_SIZE     (24304)
#define frame_47_ALIGNED  (24304)

// Source: resources/frame_48_delay-0.bin
#define frame_48_OFFSET   (0x001716A8)
#define frame_48_ADDR     (0x001716A8)
#define frame_48_SIZE     (24304)
#define frame_48_ALIGNED  (24304)

// Source: resources/frame_49_delay-0.bin
#define frame_49_OFFSET   (0x00177598)
#define frame_49_ADDR     (0x00177598)
#define frame_49_SIZE     (24304)
#define frame_49_ALIGNED  (24304)

// Source: resources/frame_50_delay-0.bin
#define frame_50_OFFSET   (0x0017D488)
#define frame_50_ADDR     (0x0017D488)
#define frame_50_SIZE     (24304)
#define frame_50_ALIGNED  (24304)

// Source: resources/frame_51_delay-0.bin
#define frame_51_OFFSET   (0x00183378)
#define frame_51_ADDR     (0x00183378)
#define frame_51_SIZE     (24304)
#define frame_51_ALIGNED  (24304)

// Source: resources/frame_52_delay-0.bin
#define frame_52_OFFSET   (0x00189268)
#define frame_52_ADDR     (0x00189268)
#define frame_52_SIZE     (24304)
#define frame_52_ALIGNED  (24304)

// Source: resources/frame_53_delay-0.bin
#define frame_53_OFFSET   (0x0018F158)
#define frame_53_ADDR     (0x0018F158)
#define frame_53_SIZE     (24304)
#define frame_53_ALIGNED  (24304)

// Source: resources/frame_54_delay-0.bin
#define frame_54_OFFSET   (0x00195048)
#define frame_54_ADDR     (0x00195048)
#define frame_54_SIZE     (24304)
#define frame_54_ALIGNED  (24304)

// Source: resources/frame_55_delay-0.bin
#define frame_55_OFFSET   (0x0019AF38)
#define frame_55_ADDR     (0x0019AF38)
#define frame_55_SIZE     (24304)
#define frame_55_ALIGNED  (24304)

// Source: resources/frame_56_delay-0.bin
#define frame_56_OFFSET   (0x001A0E28)
#define frame_56_ADDR     (0x001A0E28)
#define frame_56_SIZE     (24304)
#define frame_56_ALIGNED  (24304)

// Source: resources/frame_57_delay-0.bin
#define frame_57_OFFSET   (0x001A6D18)
#define frame_57_ADDR     (0x001A6D18)
#define frame_57_SIZE     (24304)
#define frame_57_ALIGNED  (24304)

// Source: resources/frame_58_delay-0.bin
#define frame_58_OFFSET   (0x001ACC08)
#define frame_58_ADDR     (0x001ACC08)
#define frame_58_SIZE     (24304)
#define frame_58_ALIGNED  (24304)

// Source: resources/frame_59_delay-0.bin
#define frame_59_OFFSET   (0x001B2AF8)
#define frame_59_ADDR     (0x001B2AF8)
#define frame_59_SIZE     (24304)
#define frame_59_ALIGNED  (24304)

// Source: resources/frame_60_delay-0.bin
#define frame_60_OFFSET   (0x001B89E8)
#define frame_60_ADDR     (0x001B89E8)
#define frame_60_SIZE     (24304)
#define frame_60_ALIGNED  (24304)

// Source: resources/frame_61_delay-0.bin
#define frame_61_OFFSET   (0x001BE8D8)
#define frame_61_ADDR     (0x001BE8D8)
#define frame_61_SIZE     (24304)
#define frame_61_ALIGNED  (24304)

// Source: resources/frame_62_delay-0.bin
#define frame_62_OFFSET   (0x001C47C8)
#define frame_62_ADDR     (0x001C47C8)
#define frame_62_SIZE     (24304)
#define frame_62_ALIGNED  (24304)

// Source: resources/frame_63_delay-0.bin
#define frame_63_OFFSET   (0x001CA6B8)
#define frame_63_ADDR     (0x001CA6B8)
#define frame_63_SIZE     (24304)
#define frame_63_ALIGNED  (24304)

// Source: resources/frame_64_delay-0.bin
#define frame_64_OFFSET   (0x001D05A8)
#define frame_64_ADDR     (0x001D05A8)
#define frame_64_SIZE     (24304)
#define frame_64_ALIGNED  (24304)

// Source: resources/frame_65_delay-0.bin
#define frame_65_OFFSET   (0x001D6498)
#define frame_65_ADDR     (0x001D6498)
#define frame_65_SIZE     (24304)
#define frame_65_ALIGNED  (24304)

// Source: resources/frame_66_delay-0.bin
#define frame_66_OFFSET   (0x001DC388)
#define frame_66_ADDR     (0x001DC388)
#define frame_66_SIZE     (24304)
#define frame_66_ALIGNED  (24304)

// Source: resources/frame_67_delay-0.bin
#define frame_67_OFFSET   (0x001E2278)
#define frame_67_ADDR     (0x001E2278)
#define frame_67_SIZE     (24304)
#define frame_67_ALIGNED  (24304)

// Source: resources/frame_68_delay-0.bin
#define frame_68_OFFSET   (0x001E8168)
#define frame_68_ADDR     (0x001E8168)
#define frame_68_SIZE     (24304)
#define frame_68_ALIGNED  (24304)

// Source: resources/frame_69_delay-0.bin
#define frame_69_OFFSET   (0x001EE058)
#define frame_69_ADDR     (0x001EE058)
#define frame_69_SIZE     (24304)
#define frame_69_ALIGNED  (24304)

// Source: resources/frame_70_delay-0.bin
#define frame_70_OFFSET   (0x001F3F48)
#define frame_70_ADDR     (0x001F3F48)
#define frame_70_SIZE     (24304)
#define frame_70_ALIGNED  (24304)

// Source: resources/frame_71_delay-0.bin
#define frame_71_OFFSET   (0x001F9E38)
#define frame_71_ADDR     (0x001F9E38)
#define frame_71_SIZE     (24304)
#define frame_71_ALIGNED  (24304)

// Source: resources/frame_72_delay-0.bin
#define frame_72_OFFSET   (0x001FFD28)
#define frame_72_ADDR     (0x001FFD28)
#define frame_72_SIZE     (24304)
#define frame_72_ALIGNED  (24304)

// Source: resources/frame_73_delay-0.bin
#define frame_73_OFFSET   (0x00205C18)
#define frame_73_ADDR     (0x00205C18)
#define frame_73_SIZE     (24304)
#define frame_73_ALIGNED  (24304)

#define TOTAL_PACK_SIZE       (2145032)
#define TOTAL_RESOURCE_COUNT  (83)

#endif // __RESOURCE_MAP_H__